[build]
  publish = "." # Directorio donde se encuentran tus archivos HTML, CSS, JS (la raíz del proyecto)
  functions = "netlify/functions" # Directorio donde se encuentran tus Netlify Functions

[functions]
  node_bundler = "esbuild" # Se recomienda para un mejor rendimiento

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  