[build]
  # Ahora, 'publish' debe apuntar a la carpeta 'chat' donde están tus archivos del sitio
  publish = "chat"
  functions = "netlify/functions" # Este sigue siendo el directorio para las Netlify Functions

[functions]
  node_bundler = "esbuild" # Se recomienda para un mejor rendimiento

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  # Esta regla redirige la raíz de tu dominio Netlify a chat-bot.html dentro de la carpeta 'chat'.
  # Así, al acceder a 'solutionsads.netlify.app/' cargará directamente 'chat/chat-bot.html'
  from = "/*"
  to = "/chat-bot.html" # Ruta relativa a la carpeta 'publish' (es decir, dentro de 'chat/')
  status = 200