[build]
  publish = "." # Directorio donde se encuentran tus archivos HTML, CSS, JS (la raíz del proyecto)
  functions = "netlify/functions" # Directorio donde se encuentran tus Netlify Functions
  # NUEVA LÍNEA: Comando para reemplazar la URL de Apps Script en tu archivo JavaScript del chatbot.
  # Netlify inyecta el valor de la variable de entorno 'VITE_APPS_SCRIPT_API_URL' durante el build.
  # Asegúrate de que 'chatbot_est.js' es el nombre exacto de tu archivo JS y está en el directorio 'publish'.
  command = "sed -i 's|__APPS_SCRIPT_API_URL_PLACEHOLDER__|'$VITE_APPS_SCRIPT_API_URL'|g' chatbot_est.js"

[functions]
  node_bundler = "esbuild" # Se recomienda para un mejor rendimiento

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html" # Esto redirige todas las rutas no encontradas a index.html.
  status = 200       # Si tu archivo principal es 'chat-bot.html', deberías renombrarlo a 'index.html'
                     # o añadir una redirección específica si quieres que /chat-bot.html sea el acceso principal.