[build]
  publish = "." # Directorio donde se encuentran tus archivos HTML, CSS, JS (la raíz del proyecto)
  functions = "netlify/functions" # Directorio donde se encuentran tus Netlify Functions
  # La línea 'command = "sed -i ..."' ha sido eliminada, ya no es necesaria con el proxy.

[functions]
  node_bundler = "esbuild" # Se recomienda para un mejor rendimiento

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html" # Esto redirige todas las rutas no encontradas a index.html.
  status = 200       # Si tu archivo principal es 'chat-bot.html', deberías renombrarlo a 'index.html'
                     # para que sea la página de aterrizaje por defecto de tu sitio de Netlify.